meta_product_name: "Emitless"
meta_title: "Emitless - Reducing emissions, one purchase at a time"
meta_description: "Emitless helps consumers make smarter decisions to reduce their carbon footprint"
meta_image: "home-img.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
